spring:

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: false       # 개발 중엔 DB를 밀어야 할 수도 있으니 허용
    baseline-on-migrate: true   # 팀원들 로컬 DB에 장부 자동 생성
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate

# 다른 서비스 URL (Docker 환경)
custom:
  global:
    productServiceUrl: ${PRODUCT_SERVICE_URL}
    paymentServiceUrl: ${PAYMENT_SERVICE_URL}

swagger:
  server:
    url: http://localhost:8080
    description: Docker API Gateway