spring:
  application:
    name: market-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false

  datasource:
    url: jdbc:h2:mem:market_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

custom:
  global:
    productServiceUrl: http://localhost:8081
    paymentServiceUrl: http://localhost:8083

jwt:
  secret: ${JWT_SECRET_KEY:}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock"

market:
  metrics:
    enabled: false
