services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonar-db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/${SONAR_POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${SONAR_POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  sonar-db:
    image: postgres:16
    container_name: sonar-db
    environment:
      POSTGRES_USER: ${SONAR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONAR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SONAR_POSTGRES_DB}
    volumes:
      - sonar_postgres:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonar_postgres:
