# ============================================
# 공통 설정
# ============================================
server:
  port: 8082

spring:
  application:
    name: product-service

  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  sql-metrics:
    enabled: true

# JWT 설정
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock"

# Actuator & Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# SpringDoc
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false

product:
  inbox:
    enabled: true
  kafka:
    consumer-group: product-service
  outbox:
    enabled: true
    poller:
      interval-ms: 3000
