spring:
  datasource:
    url: jdbc:h2:mem:product_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  kafka:
    listener:
      auto-startup: false

# 테스트에서는 환경 변수 대신 application-test.yml에 JWT 시크릿 키를 직접 설정
jwt:
  secret: thock-test-jwt-secret-key-which-is-long-enough-32chars
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock-test"

product:
  inbox:
    enabled: false
  outbox:
    enabled: false
